### ISSUE TITLE
Evaluation Plots Stationary MM

### ISSUE THREAD

**Issue by alexlafleur** [ag-csw/LDStreamHMMLearn#1]
## Perfomance Stationary

![performance](https://cloud.githubusercontent.com/assets/4387137/19194891/912eb1c4-8caf-11e6-8b37-3c05a31e388d.png)
## Error Stationary

![error](https://cloud.githubusercontent.com/assets/4387137/19194899/9bdf263a-8caf-11e6-8614-2385c70d612d.png)

**Comment by alexlafleur** [comment]
## Performance and Error Evaluation on a 4x4 Heatmap

![performance](https://cloud.githubusercontent.com/assets/4387137/18780830/9f4d25b4-817f-11e6-8b6e-8bc81c6d64cd.png)
![error](https://cloud.githubusercontent.com/assets/4387137/18780829/9f328218-817f-11e6-864e-6c531d698c1c.png)

**Comment by alexlafleur** [comment]
## Performance and Error Evaluation with fixed numsteps, and adapted parameters for scale_win, num_traj and eta
![performance](https://cloud.githubusercontent.com/assets/4387137/18947338/0755c97e-8633-11e6-8969-b6b55e026a9a.png)
![error](https://cloud.githubusercontent.com/assets/4387137/18947339/07563d3c-8633-11e6-9541-a3075b8dbbbd.png)

**Comment by greenTara** [comment]
There is no text here, only plots. Can this issue be closed?

**Comment by alexlafleur** [comment]
I think so, because the plots are outdated
