### ISSUE TITLE
Determination of Effective Window Size in Bayes Calculation

### ISSUE THREAD

**Issue by greenTara** [ag-csw/LDStreamHMMLearn#15]
The formula currently used for the effective window size is not completely accurate. There is a small underestimate of the effective window size (for a given value of "r").

**Comment by alexlafleur** [comment]
Any ideas on that yet?

**Comment by alexlafleur** [comment]
We need a skript that takes a fixed dataset with fixed set of parameters - only window_size and r are varying:
taumeta=4
shift=64
num_trajectories=2
len_trajectory=8^k+16*shift
num_estimations = 16
num_states=4

window_size= range(128,  8^k > 4000), increasing by a factor of 2
Take the latest error within each of the window_size varying runs, run this all together 8 times with new samples, and average the errors.

The output should be two point plots showing LOG values: 
* error vs. window_size of naive data
* error vs. shift/(1-r) for the bayes data

**Comment by alexlafleur** [comment]
![effective_window_size_plot](https://cloud.githubusercontent.com/assets/4387137/19602502/bece5fb8-97ad-11e6-82e7-0ca9c8d80aee.png)

* avg naive errors: [-2.996661227033832, -3.6282656625143366, -4.193387052940573, -5.000279866151219, -5.51165443083886, -5.852602018951411]
* avg bayes errors: [-3.4907414856780528, -4.057416865092362, -4.706620745143457, -5.367587491989275, -5.645422792186476, -5.986617893284723]

**Comment by alexlafleur** [comment]
![effective_window_size_plot_numtraj](https://cloud.githubusercontent.com/assets/4387137/19604261/c6fd9c06-97b4-11e6-8f28-2064e0db8290.png)

**Comment by alexlafleur** [comment]
num_trajectories=8
![effective_window_size_plot](https://cloud.githubusercontent.com/assets/4387137/19604567/236e1a5a-97b6-11e6-9614-12eaa23b3b71.png)

**Comment by greenTara** [comment]
The first task is to increase the number of runs (num_runs) so that the statistical fluctuations in these plots are smoothed out.  Let's put num_trajectory back to 2 - all that is doing is reducing the error of the estimation, and that is not what we care about at this point.

Once we have enough runs so that we see a smooth dependency in these point plots, we need to see if there is an effect from num_estimations. I would like to perform the calculation over a range of num_estimations (1, 2, 4, 8, 16), and plot these as separate curves on the same graphs, with the axes the same as before.

**Comment by alexlafleur** [comment]
### num_runs = 256, num_estimations = 8
![effective_window_size_plot_256](https://cloud.githubusercontent.com/assets/4387137/19684408/51177240-9ab7-11e6-8f67-a81b01ee25eb.png)

**Comment by alexlafleur** [comment]
![effective_window_size_plot](https://cloud.githubusercontent.com/assets/4387137/19687710/d9b69482-9ac6-11e6-8062-855e7bf63953.png)

**Comment by alexlafleur** [comment]
### Output Error Estimation

Num_estimations:  1
window_size: 256
### Bayes last error ### 0.0578097970011
### Bayes Error estimation ### 0.8385254915624212

Num_estimations:  1
window_size: 512
### Bayes last error ### 0.0492456243504
### Bayes Error estimation ### 0.9280776503073436

Num_estimations:  1
window_size: 1024
### Bayes last error ### 0.0256948182109
### Bayes Error estimation ### 0.9663528810041392

Num_estimations:  1
window_size: 2048
### Bayes last error ### 0.020388210902
### Bayes Error estimation ### 0.9837702755613856

Num_estimations:  1
window_size: 4096
### Bayes last error ### 0.0186863466278
### Bayes Error estimation ### 0.9920356213726731

Num_estimations:  1
window_size: 8192
### Bayes last error ### 0.0168205064681
### Bayes Error estimation ### 0.9960556920578828
[ 0.054639    0.05035514  0.02652538  0.02094507  0.01744038  0.01600789]
[ 0.0578098   0.04924562  0.02569482  0.02038821  0.01868635  0.01682051]
Final avg naive errors: [-4.193925036445245, -4.311717184172389, -5.236482633468188, -5.577245575608623, -5.841424301898359, -5.965073285765985]
Final avg bayes errors: [-4.112542183430326, -4.343860648117489, -5.282378744567749, -5.6161210076560195, -5.741871654782185, -5.893635043756692]

Num_estimations:  2
window_size: 256
### Bayes last error ### 0.0598725498608
### Bayes Error estimation ### 0.8139189901577688

Num_estimations:  2
window_size: 512
### Bayes last error ### 0.0469703118369
### Bayes Error estimation ### 0.9001889464607975

Num_estimations:  2
window_size: 1024
### Bayes last error ### 0.05121792886
### Bayes Error estimation ### 0.9478458541033584

Num_estimations:  2
window_size: 2048
### Bayes last error ### 0.0517199209453
### Bayes Error estimation ### 0.9728837703165384

Num_estimations:  2
window_size: 4096
### Bayes last error ### 0.0465263039284
### Bayes Error estimation ### 0.9859713265380898

Num_estimations:  2
window_size: 8192
### Bayes last error ### 0.0258213572849
### Bayes Error estimation ### 0.9927876654838499
[ 0.05565918  0.03473039  0.05278184  0.06039082  0.05134034  0.02746926]
[ 0.05987255  0.04697031  0.05121793  0.05171992  0.0465263   0.02582136]
Final avg naive errors: [-4.167236491674697, -4.847657746151006, -4.2438146430587995, -4.049526901446828, -4.2837632670055035, -5.186038077387158]
Final avg bayes errors: [-4.061961476521674, -4.412107018065463, -4.287207275064352, -4.273136119806327, -4.425809606505367, -5.275291352697439]

Num_estimations:  4
window_size: 256
### Bayes last error ### 0.126634673817
### Bayes Error estimation ### 0.8268333538492765

Num_estimations:  4
window_size: 512
### Bayes last error ### 0.113786903792
### Bayes Error estimation ### 0.8754105876434843

Num_estimations:  4
window_size: 1024
### Bayes last error ### 0.0818643597211
### Bayes Error estimation ### 0.9237817600578855

Num_estimations:  4
window_size: 2048
### Bayes last error ### 0.145020430086
### Bayes Error estimation ### 0.9562362669229613

Num_estimations:  4
window_size: 4096
### Bayes last error ### 0.0792382826428
### Bayes Error estimation ### 0.9757972645591936

Num_estimations:  4
window_size: 8192
### Bayes last error ### 0.0781821679061
### Bayes Error estimation ### 0.9869771232495737
[ 0.14933793  0.06942047  0.07233388  0.14195867  0.08064992  0.07774695]
[ 0.12663467  0.1137869   0.08186436  0.14502043  0.07923828  0.07818217]
Final avg naive errors: [-2.7433474603650825, -3.848495127659358, -3.7891847372482896, -2.8164571109257963, -3.632183173182028, -3.685070185632032]
Final avg bayes errors: [-2.9812556119678497, -3.135593573464167, -3.610620689613037, -2.7856719373581402, -3.6576585772104693, -3.677016600234746]

Num_estimations:  8
window_size: 256
### Bayes last error ### 0.0626126318488
### Bayes Error estimation ### 0.878195270784595

Num_estimations:  8
window_size: 512
### Bayes last error ### 0.0576248729981
### Bayes Error estimation ### 0.8685646841161665

Num_estimations:  8
window_size: 1024
### Bayes last error ### 0.0225784589422
### Bayes Error estimation ### 0.8994790632381691

Num_estimations:  8
window_size: 2048
### Bayes last error ### 0.0214339286885
### Bayes Error estimation ### 0.9338814973069959

Num_estimations:  8
window_size: 4096
### Bayes last error ### 0.0122356038122
### Bayes Error estimation ### 0.960006316535861

Num_estimations:  8
window_size: 8192
### Bayes last error ### 0.00982246905672
### Bayes Error estimation ### 0.977138842772168
[ 0.08178217  0.07386466  0.02677519  0.02198473  0.01182446  0.01236095]
[ 0.06261263  0.05762487  0.02257846  0.02143393  0.0122356   0.00982247]
Final avg naive errors: [-3.612069851397604, -3.7589718745784646, -5.222959418705164, -5.50735414168971, -6.402081396050028, -6.338066480050502]
Final avg bayes errors: [-3.9974024452821233, -4.1171645238455055, -5.468909169222674, -5.54395987965836, -6.3527708913503655, -6.669698566827819]

Num_estimations:  16
window_size: 256
### Bayes last error ### 0.055978194767
### Bayes Error estimation ### 0.917270231955385

Num_estimations:  16
window_size: 512
### Bayes last error ### 0.0445148935915
### Bayes Error estimation ### 0.8852220960798642

Num_estimations:  16
window_size: 1024
### Bayes last error ### 0.0271416824531
### Bayes Error estimation ### 0.8854987289092617

Num_estimations:  16
window_size: 2048
### Bayes last error ### 0.0366817248055
### Bayes Error estimation ### 0.9098979050494661

Num_estimations:  16
window_size: 4096
### Bayes last error ### 0.0168791782859
### Bayes Error estimation ### 0.9384584445629821

Num_estimations:  16
window_size: 8192
### Bayes last error ### 0.0209108144403
### Bayes Error estimation ### 0.9617584009802518
[ 0.06811342  0.0753198   0.03442242  0.0525533   0.02987929  0.02313014]
[ 0.05597819  0.04451489  0.02714168  0.03668172  0.01687918  0.02091081]
Final avg naive errors: [-3.875917089227374, -3.7308269512066743, -4.860507556017364, -4.250074938602584, -5.0647101942427675, -5.434082427358724]
Final avg bayes errors: [-4.158991227384248, -4.489568082555755, -5.203346036756806, -4.7687947125138965, -5.888611517464198, -5.579606936261932]

Process finished with exit code 0

**Comment by greenTara** [comment]
The goal is to optimize the script so that a large number of runs can be made without unnecessary calculation. There are several points to address, some already completed:
1. Since the naive algorithm should have the same expected error for all values k = 0 to num_estimations, then we omitted these estimations, except for the k=0 case, which is needed to set the prior in the bayes estimations. DONE
2. Now the input and output signatures of the methods need to be fixed to accommodate this change.
  a) performance_and_error_calculation returns errbayes, not err. Also err is omitted from the call sequence DONE
  b) err is removed from the call sequence and return values where performance_and_error_calculation is called in get_errors DONE
  c) avg_err_final is removed from the return sequence of get_errors. Also remove this from the statement where get_errors is called. (TODO)
      Note that all statements involved in calculating avg_err_final can be deleted.
     But the place where this return value is used in the main test script needs to be updated
                naive[time] = avg_err_final
       =>
                naive = avg_err_bayes[0]
     The loop at line 23 can be deleted altogether.
  d) avg_err_bayes_final is renamed to avg_err_bayes. It appears that all statements relevant to this return value are still correct
  e) the self.times array is no longer needed. The plots will, I think, use all values k = 0, 1, ..., 16, for the bayes case and that is OK.
     
As far as I can tell, that is all that must be changed regarding the plots. 

For checking the formula, add the following set of print statements, one set for each point on the graph:
1. Window Size: window_size
2. Number of Estimations: num_estimations
3. Shift
4. Actual Expected Bayes/Naive Ratio:   bayes[k]/bayes[0]
5. Theoretical Bound for Expected Bayes/Naive Ratio: the formula


Another optimization:
* set num_trajectories = 1
* as it is currently being used, effective_window_size is redundant because it is the same as window_size. Remove this array and use window_size only.

There are a few places where renaming variables will lead to code that is more self-documenting.

1. When taking the log for plotting, don't reuse the same variable name, add "log" to it somewhere.

That should do it. The number of runs will need to be at least 256, and may need to be more to get stable values for the expectation of the error.

**Comment by greenTara** [comment]
Please increase the number of runs by a factor of 2 - we should be able to
get smoother curves.

**Comment by alexlafleur** [comment]
## Exemplary plot for num_runs=8
![effective_window_size_plot](https://cloud.githubusercontent.com/assets/4387137/19768134/827c54ae-9c56-11e6-8204-e35b2206066f.png)

**Comment by greenTara** [comment]
There has been no further comments on this issue for 15 days, but there was I believe some additional work on this script. Is there a related issue?

**Comment by greenTara** [comment]
I have an improved formula for the expectation of the error in the MM case:

err_bayes/err_naive = math.sqrt( (1+math.pow(r,2*k+1))/((1+r) ))

**Comment by greenTara** [comment]
Discussion continuing on #31
