### ISSUE TITLE
New Naive Test for Revision

### ISSUE THREAD

**Issue by alexlafleur** [ag-csw/LDStreamHMMLearn#17]
![error](https://cloud.githubusercontent.com/assets/4387137/19394471/9d46d092-9239-11e6-852a-280db2e24398.png)

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

Parameter Overview for ETA:
taumeta:     2
eta:     8
scale_window    : 16
shift:   16
window_size:     256
num_estimations:     256
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4369

Parameter Overview for ETA:
taumeta:     2
eta:     16
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     2
eta:     32
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     8
scale_window    : 16
shift:   32
window_size:     544
num_estimations:     119
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4385

Parameter Overview for ETA:
taumeta:     4
eta:     16
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     4
eta:     32
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     8
scale_window    : 16
shift:   64
window_size:     1088
num_estimations:     51
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4417

Parameter Overview for ETA:
taumeta:     8
eta:     16
scale_window    : 16
shift:   128
window_size:     2176
num_estimations:     17
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4481

Parameter Overview for ETA:
taumeta:     8
eta:     32
scale_window    : 16
shift:   256
window_size:     4352
num_estimations:     0
len_trajectory:  4353
num_trajectories:    2
num_trajectories*len_trajectory:     8706
lentraj + shift:     4609

NAIVE [[-2.61988819 -3.58119498 -4.45343235]
 [-3.21427674 -4.25882583 -5.03847377]
 [-3.88555725 -4.85900159 -5.52139723]]

NAIVE NEW [[-2.6253458  -3.62263093 -4.59839795]
 [-3.20867991 -4.09889392 -4.94297356]
 [-3.69264784 -4.56031739 -5.7131062 ]]

BAYES [[-3.16161486 -4.10797364 -5.14289459]
 [-3.66532791 -4.68221163 -5.19620955]
 [-4.26999306 -4.99908179 -5.52139723]]

**Comment by alexlafleur** [comment]
The corresponding code can be found new_naive_evaluation.py

**Comment by greenTara** [comment]
This script has been supereded.
