### ISSUE TITLE
Heatmaps created for nonzero delta

### ISSUE THREAD

**Issue by greenTara** [ag-csw/LDStreamHMMLearn#20]
Start with delta = 1/8 or even less and there should be not much change in the heatmaps.S

So we need to see how the observed change, with changing delta, compares to the accuracy, as found by comparing the average over 4 runs versus 8 runs.

**Comment by alexlafleur** [comment]
### Plots for delta=1/8
![error0 125](https://cloud.githubusercontent.com/assets/4387137/20218120/4c6495a6-a823-11e6-8297-9a414dd6a76c.png)
![performance0 125](https://cloud.githubusercontent.com/assets/4387137/20218121/4c7e3d76-a823-11e6-93bb-01f66a86bfb4.png)

**Comment by greenTara** [comment]
This issue is following up on https://github.com/ag-csw/LDStreamHMMLearn/issues/4

**Comment by greenTara** [comment]
discussion is continuing at #25
