### ISSUE TITLE
Check into using numpy array routines to better advantage

### ISSUE THREAD

**Issue by greenTara** [ag-csw/LDStreamHMMLearn#24]
Currently we do something like the following quite a few times:
                for i in range(0, self.num_trajectories):
                    dataslice0.append(data0[i, :])

There are some numpy methods that might speed this up. Something like:
dataslice0 = data0.flat.split(m)

(but checking that the elements come out in the right order)

**Comment by alexlafleur** [comment]
I think is issue can be closed, too

**Comment by greenTara** [comment]
Somehow, this code is still appearing in util_evaluation_holder

            dataslice0 = []

            for i in range(0, self.num_trajectories):
                dataslice0.append(data0[i, :])

lines 159-162, 201-203, 223-225

**Comment by alexlafleur** [comment]
I fixed that.

**Comment by greenTara** [comment]
I think you can also delete the lines

dataslice0 = []

**Comment by greenTara** [comment]
Done and verified.
