### ISSUE TITLE
Details on Plots

### ISSUE THREAD

**Issue by alexlafleur** [ag-csw/LDStreamHMMLearn#3]
## Nonstationary

![error_separate_colorbars-nonstat](https://cloud.githubusercontent.com/assets/4387137/18709998/322b9272-8003-11e6-9c0a-db4bb2b7709f.png)

![performance_separate_colorbars-nonstat](https://cloud.githubusercontent.com/assets/4387137/18709958/ff971192-8002-11e6-96cd-adce71a8878c.png)
## Stationary

![error_separate_colorbars](https://cloud.githubusercontent.com/assets/4387137/18709976/12673b8a-8003-11e6-92af-12aaf62fb273.png)
![performance_separate_colorbars](https://cloud.githubusercontent.com/assets/4387137/18709977/126b8d70-8003-11e6-9cc9-ea9ada65903c.png)

**Comment by alexlafleur** [comment]
![heatmap error taumeta numsteps](https://cloud.githubusercontent.com/assets/4387137/18710669/b9a2fba2-8006-11e6-942f-9bb70135932e.png)
![heatmap performance taumeta numsteps](https://cloud.githubusercontent.com/assets/4387137/18710670/b9bb51a2-8006-11e6-91ad-da68178a79f6.png)

**Comment by alexlafleur** [comment]
## Performance and Error Evaluation with Separate Colorbars on a 4x4 Heatmap

![performance_separate_colorbars](https://cloud.githubusercontent.com/assets/4387137/18780918/f7c188e8-817f-11e6-828c-6f32b34e7eaa.png)
![error_separate_colorbars](https://cloud.githubusercontent.com/assets/4387137/18780916/f7a539a4-817f-11e6-8294-549a75e0d128.png)

**Comment by alexlafleur** [comment]
## Performance and Error Evaluation with fixed numsteps, and adapted parameters scale_win, num_traj, eta with separate colorbars
![performance_separate_colorbars](https://cloud.githubusercontent.com/assets/4387137/18947458/736e45d2-8633-11e6-8940-8d5d8fcea9a2.png)
![error_separate_colorbars](https://cloud.githubusercontent.com/assets/4387137/18947457/7366a78c-8633-11e6-92eb-b6d52b1cc0cf.png)

**Comment by greenTara** [comment]
There is no text here, only output and plots. Can this issue be closed?

**Comment by alexlafleur** [comment]
Yes.
