### ISSUE TITLE
Save time during simulation by subsampling

### ISSUE THREAD

**Issue by greenTara** [ag-csw/LDStreamHMMLearn#30]
It is not necessary to re-simulate trajectories for smaller values of taumeta, because we can get them by subsampling.

Subsampling by a factor of n is taking only the trajectory values every n steps.

**Comment by alexlafleur** [comment]
/home/alexandra/miniconda3/bin/python /home/alexandra/pycharm-community-2016.2.2/helpers/pycharm/utrunner.py /home/alexandra/GIT/LDStreamHMMLearn/ldshmm/evaluation/complete_test_taumeta_stationary_bayes_only.py::Approach_Test::test_run_all_tests true
Testing started at 15:48 ...
Starting Run 0
Simulating data
Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 2
eta:	 8
scale_window	: 16
shift:	 16
window_size:	 256
num_estimations:	 256
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 65792
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 2
eta:	 16
scale_window	: 16
shift:	 32
window_size:	 512
num_estimations:	 120
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 61952
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 2
eta:	 32
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 4
eta:	 8
scale_window	: 16
shift:	 32
window_size:	 512
num_estimations:	 120
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 61952
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 4
eta:	 16
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 4
eta:	 32
scale_window	: 16
shift:	 128
window_size:	 2048
num_estimations:	 18
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 38912
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 8
eta:	 8
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 8
eta:	 16
scale_window	: 16
shift:	 128
window_size:	 2048
num_estimations:	 18
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 38912
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 8
eta:	 32
scale_window	: 16
shift:	 256
window_size:	 4096
num_estimations:	 1
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 8192
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 2
eta:	 16
scale_window	: 8
shift:	 32
window_size:	 256
num_estimations:	 128
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 33024
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 2
eta:	 16
scale_window	: 16
shift:	 32
window_size:	 512
num_estimations:	 120
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 61952
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 2
eta:	 16
scale_window	: 32
shift:	 32
window_size:	 1024
num_estimations:	 104
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 107520
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 4
eta:	 16
scale_window	: 8
shift:	 64
window_size:	 512
num_estimations:	 60
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 31232
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 4
eta:	 16
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 4
eta:	 16
scale_window	: 32
shift:	 64
window_size:	 2048
num_estimations:	 36
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 75776
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 8
eta:	 16
scale_window	: 8
shift:	 128
window_size:	 1024
num_estimations:	 26
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 27648
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 8
eta:	 16
scale_window	: 16
shift:	 128
window_size:	 2048
num_estimations:	 18
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 38912
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 8
eta:	 16
scale_window	: 32
shift:	 128
window_size:	 4096
num_estimations:	 2
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 12288
BAYES window_size + num_estimations*shift	 4352


Starting Run 1
Simulating data
Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 2
eta:	 8
scale_window	: 16
shift:	 16
window_size:	 256
num_estimations:	 256
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 65792
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 2
eta:	 16
scale_window	: 16
shift:	 32
window_size:	 512
num_estimations:	 120
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 61952
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 2
eta:	 32
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 4
eta:	 8
scale_window	: 16
shift:	 32
window_size:	 512
num_estimations:	 120
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 61952
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 4
eta:	 16
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 4
eta:	 32
scale_window	: 16
shift:	 128
window_size:	 2048
num_estimations:	 18
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 38912
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 8
eta:	 8
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 8
eta:	 16
scale_window	: 16
shift:	 128
window_size:	 2048
num_estimations:	 18
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 38912
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for ETA:
taumeta:	 8
eta:	 32
scale_window	: 16
shift:	 256
window_size:	 4096
num_estimations:	 1
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 8192
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 2
eta:	 16
scale_window	: 8
shift:	 32
window_size:	 256
num_estimations:	 128
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 33024
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 2
eta:	 16
scale_window	: 16
shift:	 32
window_size:	 512
num_estimations:	 120
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 61952
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 2
eta:	 16
scale_window	: 32
shift:	 32
window_size:	 1024
num_estimations:	 104
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 107520
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 4
eta:	 16
scale_window	: 8
shift:	 64
window_size:	 512
num_estimations:	 60
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 31232
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 4
eta:	 16
scale_window	: 16
shift:	 64
window_size:	 1024
num_estimations:	 52
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 54272
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 4
eta:	 16
scale_window	: 32
shift:	 64
window_size:	 2048
num_estimations:	 36
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 75776
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 8
eta:	 16
scale_window	: 8
shift:	 128
window_size:	 1024
num_estimations:	 26
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 27648
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 8
eta:	 16
scale_window	: 16
shift:	 128
window_size:	 2048
num_estimations:	 18
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 38912
BAYES window_size + num_estimations*shift	 4352


Actual processed trajectory length: 4353
Parameter Overview for scale_window:
taumeta:	 8
eta:	 16
scale_window	: 32
shift:	 128
window_size:	 4096
num_estimations:	 2
len_trajectory:	 4353
num_trajectories:	 4
num_trajectories*len_trajectory:	 17412
NAIVE window_size * num_estimations	 12288
BAYES window_size + num_estimations*shift	 4352


GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(python:7664): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(python:7664): Gtk-WARNING **: Loading IM context type 'ibus' failed

(python:7664): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(python:7664): Gtk-WARNING **: Loading IM context type 'ibus' failed

(python:7664): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(python:7664): Gtk-WARNING **: Loading IM context type 'ibus' failed
BAYES ETA ERR [array([[-2.67295348, -3.79272086, -5.3142642 ],
       [-3.23621053, -4.41399469, -5.88298108],
       [-3.77692474, -4.96310555, -5.86223308]]), array([[-2.4982584 , -3.82999517, -5.20234306],
       [-2.89523981, -4.3143312 , -5.49304183],
       [-3.40388996, -4.56469682, -5.89114126]])] MEAN ARRAY [[-2.58560594 -3.81135802 -5.25830363]
 [-3.06572517 -4.36416294 -5.68801145]
 [-3.59040735 -4.76390118 -5.87668717]]
BAYES SCALEWIN ERR [array([[-2.64075379, -3.74429135, -5.29468601],
       [-3.23621053, -4.41399469, -5.88298108],
       [-3.80556082, -4.97620511, -5.86325202]]), array([[-2.47389913, -3.8216604 , -5.18488019],
       [-2.89523981, -4.3143312 , -5.49304183],
       [-3.40561738, -4.57246135, -5.88432557]])] MEAN ARRAY [[-2.55732646 -3.78297588 -5.2397831 ]
 [-3.06572517 -4.36416294 -5.68801145]
 [-3.6055891  -4.77433323 -5.8737888 ]]
Average Errors Run 1-2: 
[array([[-2.58560594, -3.81135802, -5.25830363],
       [-3.06572517, -4.36416294, -5.68801145],
       [-3.59040735, -4.76390118, -5.87668717]]), array([[-2.55732646, -3.78297588, -5.2397831 ],
       [-3.06572517, -4.36416294, -5.68801145],
       [-3.6055891 , -4.77433323, -5.8737888 ]])]
Average Errors Run 1-4: 
[]
Average Errors Run 1-2: 
[array([[-2.58560594, -3.81135802, -5.25830363],
       [-3.06572517, -4.36416294, -5.68801145],
       [-3.59040735, -4.76390118, -5.87668717]]), array([[-2.55732646, -3.78297588, -5.2397831 ],
       [-3.06572517, -4.36416294, -5.68801145],
       [-3.6055891 , -4.77433323, -5.8737888 ]])]

Process finished with exit code 0

**Comment by greenTara** [comment]
In order to get these plots out in a reasonable length of time, I would like to change the strategy in the nonstationary case so that we choose just a single model from the family, but average over many sample trajectories. This is just for the nonstationary case - for the stationary case we should still average over many models sampled from the family.

**Comment by alexlafleur** [comment]
You mean that I remove that part again?
`if i % numsims == 0:
      self.qmm1_0_0 = self.qmmf1_0.sample()[0]`
and do this only once in the constructor?

"average over many sample trajectories" - what is many?

**Comment by greenTara** [comment]
It would be good if we had util functions for some of these things, with input parameters.

So when we only want to average over one run, we pass num_runs = 1.

"many" is enough to get a stable value of the expectation for two significant figures. It needs to be determined with some experimentation.

**Comment by alexlafleur** [comment]
I have a "number_of_runs" parameter inside the constructor that is used for the averaging. 

For the non-stationary case we want to keep only one model from the family (which would be one call to sample) for all calculations. To average over numruns runs, we want to sample "numruns" new trajectories (so one trajectory for one path through the loop?) Do  I get this right?

**Comment by greenTara** [comment]
This done. There are some higher-level concerns about computing the lag value correctly. I will close this issue and open another one, which will have less priority.
