### ISSUE TITLE
Display percentiles along trajectory

### ISSUE THREAD

**Issue by greenTara** [ag-csw/LDStreamHMMLearn#31]
It is important that we show the distribution
of errors, as well as the average error, as is now being shown in the heatmap. Since the distribution is represented by a set of numbers rather than one number, it does not work so well as a heatmap. So let's select a single set of parameters (the mid value), and create a plot where we trace the deciles (min= 0%, 10%, 20%, ..., 90%), max = 100%) of the error on the vertical axis and the time value (index along the trajectory) as the horizontal value.
Title: Distribution of Transition Matrix Error Along Trajectory (Bayes)

and another plot for Naive.
Labels: Time, Error
All the deciles can appear on the same plot, with different colors and point symbols. Connect the points with lines.

Use the same number of runs as is being used for the average error plot (which we still investigate to see how many are necessary), and sample over many trajectories and many models from the family.

Let's do this first for the stationary Markov model, since it can be completed more quickly and we get the format worked out. 

Afterwards, we will create the same plot for a non-stationary model, averaged over many runs, but just using a single model sampled from the family.

**Comment by alexlafleur** [comment]
I wrote a new function that uses the mid values for parameters. Now, I have num_estimations- error and time values. I found the function np.percentiles:
`np.percentile(var, np.arange(0, 100, 10)) # computes deciles` but is that what you want? We need that for both error and performance values? How should that plot look like in the end?

**Comment by greenTara** [comment]
Let's ignore performance for now. Deciles is indeed what we want.

The plot should have points for each decile value, for each time value. The points for the same decile at different times should be connected by lines.

**Comment by greenTara** [comment]
And yes - the number of different values is num_estimations. Those indices go along the horizontal axis.

**Comment by greenTara** [comment]
Please add parameters to this function so that the parameters can be specified, but set the mid values as the defaults.

**Comment by alexlafleur** [comment]
![decile](https://cloud.githubusercontent.com/assets/4387137/20603698/fc5b2f08-b262-11e6-9177-ef5b4e623d74.png)

Is this what you expect to get as an output plot?
The different colors show the corresponding decile values for a timepoint of error. ("k" in num_estimations).

I ran this evaluation with 64 number of runs.

**Comment by alexlafleur** [comment]
## Naive 
![decile_naive](https://cloud.githubusercontent.com/assets/4387137/20604196/7eacdcd4-b265-11e6-8d5b-5407d479d808.png)

## Bayes
![decile_bayes](https://cloud.githubusercontent.com/assets/4387137/20604195/7eac2078-b265-11e6-953a-bf567993229d.png)

**Comment by alexlafleur** [comment]
I realized that the simulated data was created with different taumeta (max_taumeta) than was used inside the evaluation (mid_taumeta). After changing that to both mid_taumeta, I retrieved the following plots:
[decile_bayes.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/613137/decile_bayes.pdf)
[decile_naive.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/613138/decile_naive.pdf)

**Comment by greenTara** [comment]
The plots are good. The labels and scaling need some work.

Vertical: Transition Matrix Error
Horizontal: Time

To have the horizontal axis actually be "time", we need to do a transformation...

**Comment by greenTara** [comment]
Let's make the lower value on the vertical axis to be zero, since that is the theoretical minimum value of the error.

**Comment by greenTara** [comment]
current_time = window + k*shift # most recent time of all data processed
estimation_time = window/2 + k*shift # time at center of mass of weight distribution

So estimation_time is what should be plotted on the horizontal axis.

**Comment by greenTara** [comment]
Let's also coordinate these plots with the (improved) prediction in issue #15

**Comment by alexlafleur** [comment]
[Deciles_Bayes_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/627609/Deciles_Bayes_MM.pdf)

**Comment by alexlafleur** [comment]
[Deciles_Bayes_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/627695/Deciles_Bayes_MM.pdf)

I still have to change the legend, but is the overall look of the plot expected?

**Comment by greenTara** [comment]
Just a thought on these plots - we should check the shape of the error matrices - they may need to be flattened to do the statistics correctly.

**Comment by alexlafleur** [comment]
It's a ndarray of shape (53,)

**Comment by alexlafleur** [comment]
I realized that we used the complete trajectory in the above plots (where the error is decreasing over time). I reran the script with this change and it looks like this:
[Deciles_Bayes_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/633702/Deciles_Bayes_MM.pdf)

On the other hand, when I run it with the reshaped trajectories, it looks like this:
[Deciles_Bayes_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/633715/Deciles_Bayes_MM.pdf)

Maybe thats the issue here?

**Comment by alexlafleur** [comment]
Plot with shape AVG_ERRORS_ND (256, 53):
[Deciles_Bayes_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/633923/Deciles_Bayes_MM.pdf)

**Comment by alexlafleur** [comment]
[Deciles_Bayes_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/634189/Deciles_Bayes_MM.pdf)

**Comment by greenTara** [comment]
Let's also coordinate these plots with the (improved) prediction in issue #15

I have an improved formula for the expectation of the error in the MM case:

err_bayes[k]/err_naive = math.sqrt( (1+math.pow(r,2*k+1))/((1+r) ))

**Comment by alexlafleur** [comment]
[Deciles_Bayes_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/634447/Deciles_Bayes_MM.pdf)

black triangles: predicted error
green circles: mean error

I still have to add them to the legend.

**Comment by greenTara** [comment]
Plots archived in #43
