### ISSUE TITLE
Bug in nonstationary error estimation

### ISSUE THREAD

**Issue by greenTara** [ag-csw/LDStreamHMMLearn#36]
The time value that goes into the method .eval (on a qmm) when calculating the difference between the estimated transition matrix and the model transition matrix should be the time at the center of mass of the weight distribution.
When current_time = window_size + k * self.shift -1

For the naive algorithm the center of mass is:
dk =int((window_size-1)/2)
estimation_time = current_time - dk

For the bayes algorithm this is:
w = window_size
s = shift
dk = int(w  -( s+1)/2 - w * math.pow(r, k+1)/2 )
estimation_time = current_time - dk

**Comment by greenTara** [comment]
See also the comments on issue #4

**Comment by alexlafleur** [comment]
When I change the formulas, the plots look like this:

Old script:
![dependence_bayes_error_qmm_delta 0 5](https://cloud.githubusercontent.com/assets/4387137/20800525/0f22e8c8-b7e6-11e6-9f5c-54899a001fd2.png)

New script:
![dependence_bayes_error_qmm_delta_new 0 5](https://cloud.githubusercontent.com/assets/4387137/20800526/0f2f8254-b7e6-11e6-9042-7c187fb7bbd0.png)

**Comment by greenTara** [comment]
ok, that's more like the expected result.

**Comment by greenTara** [comment]
This appears to be resolved.
