### ISSUE TITLE
Error Plot for Paper

### ISSUE THREAD

**Issue by alexlafleur** [ag-csw/LDStreamHMMLearn#39]
### Comparison of Naive and Bayes Error MM
num_trajectories = 64
number of runs = 64

[Comparison_Naive_Bayes_Error_MM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/627276/Comparison_Naive_Bayes_Error_MM.pdf)

**Comment by alexlafleur** [comment]
### Comparison of Naive and Bayes Error QMM

num_trajectories = 16
number_of_runs = 1
delta = 1

[Comparison_Naïve_Bayes_Error_QMM.pdf](https://github.com/ag-csw/LDStreamHMMLearn/files/627428/Comparison_Naive_Bayes_Error_QMM.pdf)

**Comment by greenTara** [comment]
moved to #40 #41
