### ISSUE TITLE
Evaluation Plots Non-Stationary MM

### ISSUE THREAD

**Issue by alexlafleur** [ag-csw/LDStreamHMMLearn#4]
## Performance Non-Stationary

![performance-nonstat](https://cloud.githubusercontent.com/assets/4387137/18706126/09b07040-7ff1-11e6-85a3-11cd6b39cd4b.png)
## Error Non-Stationary

![error-nonstat](https://cloud.githubusercontent.com/assets/4387137/18706138/138284be-7ff1-11e6-871a-232ad53bec85.png)

**Comment by greenTara** [comment]
Now that we have the stationary MM case running smoothly, let's look at this non-stationary case again.

One change that needs to be made is in the temporal value that is used to get the "ground truth" transition matrix that is compared to the estimated transition matrix in each case. If my calculations are correct, this value should be:
Naive:  t_k = (w-1)/2 + k*shift
Bayes:  t_k = (k+1/2)*shift -1/2 +(w+shift*(2*k-1))*math.pow(r, k)/2

**Comment by greenTara** [comment]
The following is currently going on in the heatmap scrip for the stationary case:
1. an MMFamily1 is constructed ( a generator of scaled familes of stationary MMs)

**Comment by alexlafleur** [comment]
I wanted to run the stationary tests using the non-stationary models, and set delta to 0. The eval function needs an additional parameter "tauquasi". What value should I assign to this variable?

**Comment by alexlafleur** [comment]
### MM Performance:
![performance](https://cloud.githubusercontent.com/assets/4387137/19891345/f67eebc2-a03f-11e6-8bbb-45c5967f1f4e.png)
### QMM Performance with Delta=0:
![performance0](https://cloud.githubusercontent.com/assets/4387137/19891346/f6836cec-a03f-11e6-8073-10a963b4325c.png)

### MM Error:
![error](https://cloud.githubusercontent.com/assets/4387137/19891350/f9e2f3f8-a03f-11e6-87ec-8be8fe8f3b3d.png)
### QMM Error with Delta=0:
![error0](https://cloud.githubusercontent.com/assets/4387137/19891349/f9e2798c-a03f-11e6-877b-903535d2d30a.png)

**Comment by greenTara** [comment]
Discussion continuing at #25
