### ISSUE TITLE
MMFamily1 SampleBasis 

### ISSUE THREAD

**Issue by alexlafleur** [ag-csw/LDStreamHMMLearn#7]
## statconc = 1/64
[[  4.91444995e-29 ,   5.66891298e-06,   2.76826268e-30,   9.99994331e-01]
 [  2.15816825e-01,   4.21887223e-01,   3.34178750e-01,  -9.71882799e-01]
 [  8.44918697e-01,   8.14956100e-03,   8.54341613e-02,  -9.38502419e-01]
 [  1.58174666e-01,   1.76345880e-01,   2.84205117e-01,  -6.18725663e-01]]

**Comment by greenTara** [comment]
This looks correct. There is one dominant value (9.999e-01) in the first
row. At a glance it looks reasonable that the first row sums to one and the
other rows sum to zero, to within roundoff error. (This should be a unit
test assertion.)

On Thu, Oct 6, 2016 at 6:36 AM, Alexandra La Fleur <notifications@github.com
